#eureka:
#  client:
##    register-with-eureka: false
##    fetchRegistry: false
#    serviceUrl:
#        defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
#  server:
#    waitTimeInMsWhenSyncEmpty: 0 
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'    